<section class="ftco-section ftco-no-pb">
		<div class="container">
			<div class="row justify-content-center mb-5 pb-2">
				<div class="col-md-8 text-center heading-section ftco-animate">
					<h2 class="mb-4"><span>আমাদের সকল </span>ছাত্র-ছাত্রীর তালিকা</h2>
					<p>Separated they live in. A small river named Duden flows by their place and supplies it with the
						necessary regelialia. It is a paradisematic country</p>
				</div>
			</div>

			<div class="row">
				<div class="col-md-12">
					<table class="table table-striped table-bordered text-center" style="font-size: 20px;">
						<thead>
							<tr>
								<th>ক্রম</th>
								<th>শ্রেণী</th>
								<th>শাখা</th>
								<th>ছাত্র</th>
								<th>ছাত্রী</th>
								<th>মুসলিম</th>
								<th>হিন্দু</th>
								<th>বৌদ্ধ</th>
								<th>মোট</th>
							</tr>
						</thead>

						<tbody>
							<tr>
								<td>১</td>
								<td>৬ষ্ঠ</td>
								<td>A</td>
								<td>১০৮</td>
								<td>-</td>
								<td></td>
								<td>২</td>
								<td>১৫</td>
								<th>১০৮</th>
							</tr>
							<tr>
								<td>২</td>
								<td>৬ষ্ঠ</td>
								<td>B</td>
								<td>-</td>
								<td>১১৩</td>
								<td></td>
								<td>-</td>
								<td>২০</td>
								<th>১১৩</th>
							</tr>
							<tr>
								<td>৩</td>
								<td>৬ষ্ঠ</td>
								<td>C</td>
								<td>-</td>
								<td>১১৮</td>
								<td></td>
								<td>২</td>
								<td>১২</td>
								<th>১১৮</th>
							</tr>
							<tr>
								<td>৪</td>
								<td>৬ষ্ঠ</td>
								<td>D</td>
								<td>৯৮</td>
								<td>-</td>
								<td></td>
								<td>-</td>
								<td>৭</td>
								<th>৯৮</th>
							</tr>

							<tr>
								<td>৫</td>
								<td>৭ম</td>
								<td>A</td>
								<td>-</td>
								<td>১১১</td>
								<td></td>
								<td>২</td>
								<td>৬</td>
								<th>১১১</th>
							</tr>
							<tr>
								<td>৬</td>
								<td>৭ম</td>
								<td>B</td>
								<td>৯৬</td>
								<td>-</td>
								<td></td>
								<td>-</td>
								<td>১০</td>
								<th>৯৬</th>
							</tr>
							<tr>
								<td>৭</td>
								<td>৭ম</td>
								<td>C</td>
								<td>৯৭</td>
								<td>০</td>
								<td></td>
								<td>১</td>
								<td>৯</td>
								<th>৯৭</th>
							</tr>
							<tr>
								<td>৮</td>
								<td>৭ম</td>
								<td>D</td>
								<td>-</td>
								<td>১০৮</td>
								<td></td>
								<td>-</td>
								<td>৮</td>
								<th>১০৮</th>
							</tr>

							<tr>
								<td>৯</td>
								<td>৮ম</td>
								<td>A</td>
								<td>৭০</td>
								<td>-</td>
								<td></td>
								<td>-</td>
								<td>৭</td>
								<th>৭০</th>
							</tr>
							<tr>
								<td>১০</td>
								<td>৮ম</td>
								<td>B</td>
								<td>-</td>
								<td>১০০</td>
								<td></td>
								<td>১</td>
								<td>১৫</td>
								<th>১০০</th>
							</tr>
							<tr>
								<td>১১</td>
								<td>৮ম</td>
								<td>C</td>
								<td>৭৩</td>
								<td>-</td>
								<td></td>
								<td>২</td>
								<td>১৪</td>
								<th>৭৩</th>
							</tr>
							<tr>
								<td>১২</td>
								<td>৮ম</td>
								<td>D</td>
								<td>-</td>
								<td>১০৩</td>
								<td></td>
								<td>-</td>
								<td>১১</td>
								<th>১০৩</th>
							</tr>

							<tr>
								<td>১৩</td>
								<td>৯ম</td>
								<td>A</td>
								<td>১৩</td>
								<td>৭৪</td>
								<td></td>
								<td>-</td>
								<td>২</td>
								<th>৮৭</th>
							</tr>
							<tr>
								<td>১৪</td>
								<td>৯ম</td>
								<td>B</td>
								<td>৫২</td>
								<td>২৮</td>
								<td></td>
								<td>-</td>
								<td>২০</td>
								<th>৮০</th>
							</tr>
							<tr>
								<td>১৫</td>
								<td>৯ম</td>
								<td>C</td>
								<td>১৮</td>
								<td>৩৫</td>
								<td></td>
								<td>৫</td>
								<td>৬</td>
								<th>৫৩</th>
							</tr>
							<tr>
								<td>১৬</td>
								<td>৯ম</td>
								<td>D</td>
								<td>৩২</td>
								<td>৫৮</td>
								<td></td>
								<td>-</td>
								<td>৭</td>
								<th>৯০</th>
							</tr>

							<tr>
								<td>১৭</td>
								<td>১০ম</td>
								<td>A</td>
								<td>৩২</td>
								<td>৪৩</td>
								<td></td>
								<td>-</td>
								<td>১</td>
								<th>৭৫</th>
							</tr>
							<tr>
								<td>১৮</td>
								<td>১০ম</td>
								<td>B</td>
								<td>৬৩</td>
								<td>৭৭</td>
								<td></td>
								<td>১</td>
								<td>১৭</td>
								<th>১৪০</th>
							</tr>
							<tr>
								<td>১৯</td>
								<td>১০ম</td>
								<td>C</td>
								<td>৩৩</td>
								<td>২৮</td>
								<td></td>
								<td>১</td>
								<td>৬</td>
								<th>৬১</th>
							</tr>
							<tr>
								<td>২০</td>
								<td>১০ম</td>
								<td>D</td>
								<td>৩২</td>
								<td>৫৮</td>
								<td></td>
								<td>-</td>
								<td>৭</td>
								<th>৯০</th>
							</tr>

							<tr>
								<td>২১</td>
								<td>৯ম</td>
								<td>কম্পিউটার</td>
								<td>৭</td>
								<td>২৬</td>
								<td></td>
								<td>-</td>
								<td>৪</td>
								<th>৩৩</th>
							</tr>
							<tr>
								<td>২২</td>
								<td>৯ম</td>
								<td>সিভিল</td>
								<td>১৭</td>
								<td>১১</td>
								<td></td>
								<td>-</td>
								<td>৯</td>
								<th>২৮</th>
							</tr>
							<tr>
								<td>২৩</td>
								<td>১০ম</td>
								<td>কম্পিউটার</td>
								<td>৬</td>
								<td>১৩</td>
								<td></td>
								<td>১</td>
								<td>৭</td>
								<th>১৯</th>
							</tr>
							<tr>
								<td>২৪</td>
								<td>১০ম</td>
								<td>সিভিল</td>
								<td>১৫</td>
								<td>১০</td>
								<td></td>
								<td>-</td>
								<td>৪</td>
								<th>২৫</th>
							</tr>
							
						</tbody>

						<tfoot>
							<tr>
								<th colspan="2">মোট</th>
								<th>২৪</th>
								<th>৯০৪</th>
								<th>১০৫৬</th>
								<th></th>
								<th>২০</th>
								<th>২১৮</th>
								<th>১৯৬০</th>
							</tr>
						</tfoot>
					</table>
				</div>
			</div>


		</div>
	</section>